import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import "./globals.css";
import React from "react";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          toastClassName={() =>
            "bg-gray-900 text-white rounded-xl shadow-lg p-3 sm:p-4 text-sm sm:text-base w-[90%] sm:w-auto mx-auto sm:mx-0"
          }
         
        />
        <Navbar/>
        {children}</body>
    </html>
  );
}

