import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import "./globals.css";
import React from "react";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer
          position="top-right"
          autoClose={3000}
      className="!w-full sm:!w-auto !max-w-full sm:!max-w-sm px-2"
          toastClassName="!rounded-xl !shadow-lg !text-sm sm:!text-base !w-[95%] sm:!w-auto !mx-auto sm:!mx-0"
        
         
        />
        <Navbar/>
        {children}</body>
    </html>
  );
}

